/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./*.html",
    "./blog/**/*.html",
    "./src/**/*.{js,ts}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "secondary-container": "#cee6f5",
        "tertiary-container": "#d5d5d5",
        "on-secondary-fixed-variant": "#334a56",
        "surface-container-lowest": "#ffffff",
        "outline": "#72787c",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#b8daf0",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-dim": "#dadada",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed": "#c5e7fe",
        "on-primary-fixed": "#001e2c",
        "error-container": "#ffdad6",
        "surface-tint": "#426275",
        "on-tertiary-fixed-variant": "#474747",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#051e29",
        "primary-fixed-dim": "#a9cbe1",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed": "#cee6f5",
        "secondary": "#4b616e",
        "on-primary-container": "#3f6073",
        "on-surface-variant": "#42474c",
        "inverse-on-surface": "#f0f1f1",
        "outline-variant": "#c2c7cc",
        "on-surface": "#1a1c1c",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#b2cad8",
        "primary": "#426275",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f9",
        "background": "#f9f9f9",
        "on-tertiary-container": "#5c5c5c",
        "tertiary-fixed": "#e2e2e2",
        "inverse-primary": "#a9cbe1",
        "surface-container": "#eeeeee",
        "on-primary-fixed-variant": "#294b5d",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-low": "#f3f3f4",
        "tertiary": "#5e5e5e",
        "on-secondary-container": "#516774",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "error": "#ba1a1a",
        // Dark Mode Custom Overrides (Simulated via utilities if needed, but added here for reference)
        "dark-primary-container": "#004d66",
        "dark-on-primary-container": "#b8daf0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "clamp(1rem, 3vw, 2rem)",
        "section-gap": "clamp(3rem, 8vw, 5rem)",
        "margin-page": "5vw",
        "stack-gap": "clamp(1rem, 3vw, 1.5rem)",
        "container-max": "1100px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Newsreader", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["clamp(36px, 5vw, 48px)", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["clamp(16px, 2vw, 18px)", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["clamp(20px, 3vw, 24px)", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["clamp(28px, 4vw, 32px)", { lineHeight: "1.3", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
